package com.jinglun.news.dao;

import com.jinglun.news.entity.comment;
import com.jinglun.news.entity.commentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface commentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    long countByExample(commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    int deleteByExample(commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    int insert(comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    int insertSelective(comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    List<comment> selectByExample(commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") comment record, @Param("example") commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    int updateByExample(@Param("record") comment record, @Param("example") commentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    int updateByPrimaryKeySelective(comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    int updateByPrimaryKey(comment record);
}