package com.jinglun.news.dao;

import com.jinglun.news.entity.detail;
import com.jinglun.news.entity.detailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface detailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Fri Mar 09 00:21:20 CST 2018
     */
    long countByExample(detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Fri Mar 09 00:21:20 CST 2018
     */
    int deleteByExample(detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Fri Mar 09 00:21:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Fri Mar 09 00:21:20 CST 2018
     */
    int insert(detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Fri Mar 09 00:21:20 CST 2018
     */
    int insertSelective(detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Fri Mar 09 00:21:20 CST 2018
     */
    List<detail> selectByExample(detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Fri Mar 09 00:21:20 CST 2018
     */
    detail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Fri Mar 09 00:21:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") detail record, @Param("example") detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Fri Mar 09 00:21:20 CST 2018
     */
    int updateByExample(@Param("record") detail record, @Param("example") detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Fri Mar 09 00:21:20 CST 2018
     */
    int updateByPrimaryKeySelective(detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Fri Mar 09 00:21:20 CST 2018
     */
    int updateByPrimaryKey(detail record);
}