package com.jinglun.news.entity;

import java.util.Date;

public class comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.id
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.newsid
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    private Integer newsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.content
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.author
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.createdate
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.id
     *
     * @return the value of news_comment.id
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.id
     *
     * @param id the value for news_comment.id
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.newsid
     *
     * @return the value of news_comment.newsid
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    public Integer getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.newsid
     *
     * @param newsid the value for news_comment.newsid
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    public void setNewsid(Integer newsid) {
        this.newsid = newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.content
     *
     * @return the value of news_comment.content
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.content
     *
     * @param content the value for news_comment.content
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.author
     *
     * @return the value of news_comment.author
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.author
     *
     * @param author the value for news_comment.author
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.createdate
     *
     * @return the value of news_comment.createdate
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.createdate
     *
     * @param createdate the value for news_comment.createdate
     *
     * @mbg.generated Fri Mar 09 00:21:19 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}